version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: web_scraper_mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "30001:27017"

  fastapi:
    build: .
    restart: always
    ports:
      - "8597:8597"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
